### ISSUE TITLE
# sudo pip install pbkdf2 rlp ethereum

### ISSUE THREAD

**Issue by sullronn** [seevik2580/ethereum-wallet-recovery#3]
During trying to install these modules I got this problem:

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ePtDK8/eth-hash/setup.py", line 71, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 363, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 519, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-install-ePtDK8/eth-hash/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/usr/local/lib/python2.7/dist-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
        ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ePtDK8/eth-hash/

how can it fix?

**Comment by seevik2580** [comment]
hi i do have same error.. and it looks like some libraries are not supported for python 2.7 anymore ... but you can install oldest version of these libs..

fix that worked for me
`sudo apt-get install pandoc
sudo pip install setuptools --upgrade
sudo pip install joblib
sudo pip install pypandoc
sudo pip install markdown
sudo pip install rlp==0.6.0
sudo pip install ethereum==2.1.5`

**Comment by sullronn** [comment]
Yes! it's working! 
Thank you so much!
