### ISSUE TITLE
ImportError: No module named pbkdf2

### ISSUE THREAD

**Issue by europound** [seevik2580/ethereum-wallet-recovery#5]
~/Downloads/ethereum-wallet-recovery-master$ python louskac.py -p UTC--2017-07-12T00-06-42.772050600Z--f5751c906091b98be2a6be5ce42c573d704aedab -b 1234567890 -d 2
Traceback (most recent call last):
  File "louskac.py", line 3, in <module>
    from keys import decode_keystore_json
  File "/home/wallets/Downloads/ethereum-wallet-recovery-master/keys.py", line 2, in <module>
    import pbkdf2
ImportError: No module named pbkdf2

**Comment by europound** [comment]
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$ pip3 install pbkdf2
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.8/dist-packages (1.3)
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$

**Comment by europound** [comment]
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$ sudo -i
[sudo] password for wallets: 
root@wallets-TUF-Gaming:~# apt-get install python-pbkdf2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pbkdf2
root@wallets-TUF-Gaming:~# apt-get install python3-pbkdf2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  python3-pbkdf2
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 7,060 B of archives.
After this operation, 31.7 kB of additional disk space will be used.
Get:1 http://lt.archive.ubuntu.com/ubuntu focal/universe amd64 python3-pbkdf2 all 1.3+20110613.git2a0fb15~ds0-3.1 [7,060 B]
Fetched 7,060 B in 1s (10.1 kB/s)         
Selecting previously unselected package python3-pbkdf2.
(Reading database ... 321363 files and directories currently installed.)
Preparing to unpack .../python3-pbkdf2_1.3+20110613.git2a0fb15~ds0-3.1_all.deb ...
Unpacking python3-pbkdf2 (1.3+20110613.git2a0fb15~ds0-3.1) ...
Setting up python3-pbkdf2 (1.3+20110613.git2a0fb15~ds0-3.1) ...
root@wallets-TUF-Gaming:~# pip install pbkdf2

Command 'pip' not found, but there are 18 similar ones.

root@wallets-TUF-Gaming:~# pip3 install pbkdf2
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.8/dist-packages (1.3)
root@wallets-TUF-Gaming:~# 


wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$ python louskac.py -p UTC--2017-07-12T00-06-42.772050600Z--f5751c906091b98be2a6be5ce42c573d704aedab -b 1234567890 -d 2
Traceback (most recent call last):
  File "louskac.py", line 3, in <module>
    from keys import decode_keystore_json
  File "/home/wallets/Downloads/ethereum-wallet-recovery-master/keys.py", line 2, in <module>
    import pbkdf2
ImportError: No module named pbkdf2
wallets@wallets-TUF-Gaming:~/Downloads/ethereum-wallet-recovery-master$

**Comment by europound** [comment]
ython louskac.py -p UTC--2017-07-12T00-06-42.772050600Z--f5751c906091b98be2a6be5ce42c573d704aedab -b 1234567890 -d 2
Traceback (most recent call last):
  File "louskac.py", line 3, in <module>
    from keys import decode_keystore_json
  File "/home/wallets/Downloads/ethereum-wallet-recovery-master/keys.py", line 2, in <module>
    import pbkdf2
ImportError: No module named pbkdf2
